version: "3.8"
services:
  backend:
    build: ./backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
# Uncomment and configure postgres if you add DB usage
#  db:
#    image: postgres:14
#    environment:
#      POSTGRES_USER: user
#      POSTGRES_PASSWORD: pass
#      POSTGRES_DB: patroldb
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#volumes:
#  pgdata:
