-- users SQL dump generated by export_users_sqlite_to_postgres.py
BEGIN;
INSERT INTO users (id, username, password_hash, role, contractor_id, created_at) VALUES (1, 'admin', '$2b$12$ZPwkB0.aMtkN6As6XHsCaOsorT85/dwuFldGMjxUZnKtZ2yqCtgUS', 're_admin', 3, '2025-10-01 07:23:47') ON CONFLICT (username) DO NOTHING;
INSERT INTO users (id, username, password_hash, role, contractor_id, created_at) VALUES (2, 'wizpro_admin', '$2b$12$VvWQYCBvcZdT0EslawwG5.pMkdPemQ7Om.V.1iYNuhQbGI5oWrfNO', 'admin', 1, '2025-10-01 07:23:48') ON CONFLICT (username) DO NOTHING;
INSERT INTO users (id, username, password_hash, role, contractor_id, created_at) VALUES (3, 'paschal_admin', '$2b$12$EG1lXNZMg5/LfHu0ecZxcucOIg1xg/Y.SBi9IUJtDGpxYbqiAqHSK', 'admin', 2, '2025-10-01 07:23:49') ON CONFLICT (username) DO NOTHING;
INSERT INTO users (id, username, password_hash, role, contractor_id, created_at) VALUES (4, 'wizpro_user', '$2b$12$69EPFzXyytUJCtPlLmLZ3.F5uzd0ShOmohSfB6R1p2hqjbuy0vgDi', 'contractor', 1, '2025-10-01 07:23:49') ON CONFLICT (username) DO NOTHING;
INSERT INTO users (id, username, password_hash, role, contractor_id, created_at) VALUES (5, 'paschal_user', '$2b$12$Uu.q/YA6enohFg44QuE9jORllT3yHwwGOyew/OA0znBcGFFY5Nky.', 'contractor', 2, '2025-10-01 07:23:50') ON CONFLICT (username) DO NOTHING;
INSERT INTO users (id, username, password_hash, role, contractor_id, created_at) VALUES (6, 'avators_user', '$2b$12$GGsMDqL7.l9Wby6dj/58Le5pdtonqIByuz5LFE2zGwx8I8cH7rUbi', 'contractor', 4, '2025-10-01 07:23:51') ON CONFLICT (username) DO NOTHING;
SELECT setval(pg_get_serial_sequence('users','id'), 6, true);
COMMIT;
